# See the documentation for more information:
# https://packit.dev/docs/configuration/
upstream_project_url: https://github.com/martinpitt/python-dbusmock
# HACK: should work without, but propose_downstream fails; https://github.com/packit/packit-service/issues/1511
specfile_path: packaging/python-dbusmock.spec
issue_repository: https://github.com/martinpitt/python-dbusmock
copy_upstream_release_description: true
upstream_package_name: python-dbusmock
downstream_package_name: python-dbusmock

actions:
  create-archive:
    - ./setup.py sdist
    # spec and tarball need to be in the same directory
    - sh -c 'mv dist/*.tar.* packaging; ls packaging/python-dbusmock-*.tar.*'

srpm_build_deps:
  - python3-setuptools
  - python3-setuptools_scm

jobs:
  - job: copr_build
    trigger: pull_request
    targets:
    - fedora-all
    - centos-stream-8-x86_64
    - centos-stream-9-x86_64
  
  - job: tests
    trigger: pull_request
    targets:
      - fedora-all
      - centos-stream-8-x86_64
      - centos-stream-9-x86_64

  - job: propose_downstream
    trigger: release
    dist_git_branches:
      - fedora-all

  - job: koji_build
    trigger: commit
    dist_git_branches:
      - fedora-all

  - job: bodhi_update
    trigger: commit
    dist_git_branches:
      # rawhide updates are created automatically
      - fedora-branched
