# See the documentation for more information:
# https://packit.dev/docs/configuration/
specfile_path: packaging/python-dbusmock.spec
upstream_project_url: https://github.com/martinpitt/python-dbusmock
copy_upstream_release_description: true
upstream_package_name: python-dbusmock
downstream_package_name: python-dbusmock

synced_files:
  - src: packaging/python-dbusmock.spec
    dest: python-dbusmock.spec

jobs:
  - job: copr_build
    trigger: pull_request
    metadata:
      targets:
        - fedora-development
        - fedora-stable

  - job: propose_downstream
    trigger: release
    metadata:
      dist_git_branches:
        - fedora-development
        - fedora-stable
