#!/bin/sh
set -eux
IMAGE="$1"

if type podman >/dev/null 2>&1; then
    RUNC=podman
else
    RUNC="sudo docker"
fi

OS=${IMAGE#*/}
OS=${OS%:*}
$RUNC run --interactive --rm ${RUNC_OPTIONS:-} --volume `pwd`:/source:ro --workdir /source "$IMAGE" /bin/sh tests/run-$OS
